# 預設值（可被 ~/.config/chezmoi/chezmoi.toml 覆寫）
git:
  signing_key: ""  # 從環境變數 GPG_SIGNING_KEY 讀取
  gpg_program: ""

ssh:
  bitwarden_agent_sock: "~/.bitwarden-ssh-agent.sock"
  github_pubkey: "id_ed25519.pub"
  gitlab_pubkey: "id_ed25519.pub"

editor: "code"

# Feature flags（預設值，chezmoi init 時會互動詢問）
is_work: false
has_docker: false
has_ai_tools: true
